# Generated by Django 6.0.6 on 2026-06-08 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('worker', 'Worker'), ('contractor', 'Contractor')], max_length=20)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('language', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContractorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=200)),
                ('daily_wage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('work_type', models.CharField(max_length=100)),
                ('workers_needed', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('work', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('work_experience', models.IntegerField(default=0)),
                ('wage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gender', models.CharField(max_length=10)),
                ('emergency_contact', models.CharField(max_length=15)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
