# Generated by Django 6.0.6 on 2026-06-19 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_otp_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('daily_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('workers_needed', models.IntegerField()),
                ('days_of_work', models.IntegerField()),
                ('shift_timing', models.CharField(max_length=100)),
                ('urgent_hiring', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('active', 'Active'), ('filled', 'Filled'), ('closed', 'Closed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='accounts.contractorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
