# Generated by Django 6.0.6 on 2026-06-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('accepted', 'Accepted'), ('confirmed', 'Confirmed'), ('unavailable', 'Unavailable'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='applied', max_length=20),
        ),
    ]
